# 项目 zero-dream/ZeroWrt-Package-CI 专用

# CI 项目
name: PackageCI

# CI 权限
permissions: write-all

# CI 计划
on:
  # 自动运行: 每天早上 3 点
  schedule:
    - cron: 0 19 * * *
  # 手动运行
  workflow_dispatch:

# CI 环境
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# CI 任务
jobs:
  package_ci:
    name: PackageCI
    if: ${{github.repository}} == 'zero-dream/ZeroWrt-Package-CI'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@main

      - name: Initialize ZeroDream Project
        run: |
          source $GITHUB_WORKSPACE/Scripts/InitZeroDreamProject.sh

      - name: Setup Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Code
        run: |
          git clone https://github.com/zero-dream/ZeroWrt-Firmware-CI.git "$ZD_TempPath/ZeroWrt-Firmware-CI/"
          cp -r "$ZD_TempPath"/ZeroWrt-Firmware-CI/* "$GITHUB_WORKSPACE"
          # 后续的写法，删除$GITHUB_WORKSPACE目录下面的文件，再复制，可以保持100%完整更新

      - name: Commit And Push Change
        run: |
          git add "$GITHUB_WORKSPACE"
          # 检查是否有文件变更
          if git diff-index HEAD --quiet --; then
            echo "No changes to commit."
          else
            git commit -m "AutoUpdate [$(date)]"
            git push origin HEAD:${{github.ref}}
          fi
