# 项目 zero-dream/ZeroWrt-Package-CI 专用

name: PackageCI

permissions: write-all

on:
  # 自动运行: 每天早上 3 点
  schedule:
    - cron: 0 19 * * *
  # 手动运行
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  auto_clean:
    if: ${{github.repository}} == 'zero-dream/ZeroWrt-Package-CI'
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ZeroDream Project
        run: |
          sudo bash $GITHUB_WORKSPACE/Scripts/InitZeroDreamProject.sh

      - name: Clone Code
        run: |
          git clone https://github.com/zero-dream/ZeroWrt-Firmware-CI.git "$ZD_TempPath/ZeroWrt-Firmware-CI/"

      - name: Commit And Push Change
        run: |
          git add "$ZD_TempPath/ZeroWrt-Firmware-CI/"
          # 检查是否有文件变更
          if git diff-index HEAD --quiet --; then
            echo "No changes to commit."
          else
            git commit -m "AutoUpdate [$(date)]"
            git push origin HEAD:${{ github.ref }}
          fi
